version: '3'

services:
  web:
    build: ./app
    ports:
      - "8080:5000"
    restart: always

  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
