version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mount the local code into the container for easy development
    environment:
      - FLASK_ENV=dev  # Set the Flask environment variable
    restart: always

  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
