version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=test  # Set the Flask environment variable
    restart: always

  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
