FROM nginx:1.21-alpine AS builder

COPY nginx.conf /etc/nginx/nginx.conf

FROM nginx:1.21-alpine

COPY --from=builder /etc/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
